version: '3.9'

services:
  app:
    build: .
    command: bash run.sh
    environment:
      AFFINITY_API_KEY2: ${AFFINITY_API_KEY2}
      AFFINITY_API_KEY: ${AFFINITY_API_KEY}
      AIRTABLE_API_KEY: ${AIRTABLE_API_KEY}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
